### PR TITLE
Susanti

### PR DESCRIPTION
**Pull request by susantikcm**
Apart form task 9-10, this version also has improvement when displaying tasks by selected status.
when users select a status:
- the tasks list will be updated to show only tasks that matches the selected status.
- there will be a back button appears on the right of "Select by status" dropdown, that allows user to go back to full task list.
- users would also be able to perform the update task, update status, and delete functions while still on the selected tasks list and could choose to go back anytime to full task list by clicking on the back button.

### CODE REVIEW

**Comment by vokonick** [comment]
The tasks don't seem to be appearing on the task page

**Comment by susantikcm** [comment]
> The tasks don't seem to be appearing on the task page

Hi Nick, the Task List page does not show any task because it is retrieving the tasks item stored in the local storage.
In this case, your web browser's local storage, which is supposed to be empty at this point.

I have also fixed the addTask() function, so you can now try to add new tasks that will be saved to your browser's local storage and appears on your Task List page.

Thanks. :)

**Comment by vokonick** [comment]
Your fix looks all good, can add tasks, set to done, and delete, also saves data when refreshing page, good to merge with master.

**Comment by vokonick** [comment]
Looks good to me, all the tests seem to run without error.

**Pull request merged**
